version: '3.8'

services:

  traefik:
    image: traefik:v3.0
    env_file:
      - .env
    networks:
      - pterodactyl
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../data/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ../data/traefik/acme.json:/acme.json

networks:
  pterodactyl:
    external: true
